### ISSUE TITLE
Update to ASM 9.7.1

### ISSUE THREAD

**Issue by MarkEWaite** [jenkinsci/asm-api-plugin#48]
### What feature do you want to see added?

[ASM 9.7.1](https://asm.ow2.io/versions.html#9.7.1) has been released.  A pull request proposing it for Jenkins core has arrived as:

* https://github.com/jenkinsci/jenkins/pull/9831

#### 6 October 2024: [ASM 9.7.1 (tag ASM_9_7_1)](https://asm.ow2.io/versions.html#9.7.1)
* new Opcodes.V24 constant for Java 24
* Javadoc improvements
* new features
    * 318013: new ClassWriter setFlags() method.
    * Add ConstantDynamic serialization and Number suffixes to Textifier.
* bug fixes
    * 318014: Analyzer with a SimpleVerifier may throw an AnalyzerException on valid java code due to incompatible frame locals.
    * 318015: Valid bytecode for jvm, but failed to pass the CheckClassAdapter.
    * 318016: ClassNotFoundException with an array of the type of current class.
    * 318018: changing invokedynamic Handle itf bool flag doesn't create new methodref in symbol table.
    * 318019: Attribute::write is invoked twice.
    * Fix DUP_X1, DUP_X2, DUP2_X1, and DUP2_X2 not copying values correctly in Analyzer.
    * Fix SimpleVerifier multiple dimensions merge.
    * Fix SourceInterpreter wrongly saying that Condy long / doubles are one word elements.
    * GeneratorAdapter: fix push(Type.VOID_TYPE).
    * Fix null method parameter name in Asmifier causing NPE.

### Are you interested in contributing this feature?

Dependabot or Renovate pull request is easier to handle, though it will need an extra label added in order to create the release.

**Comment by jonesbusy** [comment]
Fixed by https://github.com/jenkinsci/asm-api-plugin/pull/49

CD will release it in some moments
